#!/bin/sh

curl -o pxiAyp8kv8JHgFVrJJLmE0tDMPKhSkFEkm8.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiAyp8kv8JHgFVrJJLmE0tDMPKhSkFEkm8.woff2
curl -o pxiAyp8kv8JHgFVrJJLmE0tMMPKhSkFEkm8.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiAyp8kv8JHgFVrJJLmE0tMMPKhSkFEkm8.woff2
curl -o pxiAyp8kv8JHgFVrJJLmE0tCMPKhSkFE.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiAyp8kv8JHgFVrJJLmE0tCMPKhSkFE.woff2
curl -o pxiDyp8kv8JHgFVrJJLmv1pVFteOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmv1pVFteOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLmv1pVGdeOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmv1pVGdeOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLmv1pVF9eOYktMqg.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmv1pVF9eOYktMqg.woff2
curl -o pxiDyp8kv8JHgFVrJJLm21lVFteOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm21lVFteOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLm21lVGdeOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm21lVGdeOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLm21lVF9eOYktMqg.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm21lVF9eOYktMqg.woff2
curl -o pxiGyp8kv8JHgFVrJJLucXtAOvWDSHFF.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiGyp8kv8JHgFVrJJLucXtAOvWDSHFF.woff2
curl -o pxiGyp8kv8JHgFVrJJLufntAOvWDSHFF.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiGyp8kv8JHgFVrJJLufntAOvWDSHFF.woff2
curl -o pxiGyp8kv8JHgFVrJJLucHtAOvWDSA.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiGyp8kv8JHgFVrJJLucHtAOvWDSA.woff2
curl -o pxiDyp8kv8JHgFVrJJLmg1hVFteOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmg1hVFteOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLmg1hVGdeOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmg1hVGdeOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLmg1hVF9eOYktMqg.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmg1hVF9eOYktMqg.woff2
curl -o pxiDyp8kv8JHgFVrJJLmr19VFteOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmr19VFteOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLmr19VGdeOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmr19VGdeOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLmr19VF9eOYktMqg.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmr19VF9eOYktMqg.woff2
curl -o pxiDyp8kv8JHgFVrJJLmy15VFteOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmy15VFteOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLmy15VGdeOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmy15VGdeOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLmy15VF9eOYktMqg.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLmy15VF9eOYktMqg.woff2
curl -o pxiDyp8kv8JHgFVrJJLm111VFteOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm111VFteOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLm111VGdeOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm111VGdeOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLm111VF9eOYktMqg.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm111VF9eOYktMqg.woff2
curl -o pxiDyp8kv8JHgFVrJJLm81xVFteOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm81xVFteOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLm81xVGdeOYktMqlap.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm81xVGdeOYktMqlap.woff2
curl -o pxiDyp8kv8JHgFVrJJLm81xVF9eOYktMqg.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiDyp8kv8JHgFVrJJLm81xVF9eOYktMqg.woff2
curl -o pxiGyp8kv8JHgFVrLPTucXtAOvWDSHFF.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiGyp8kv8JHgFVrLPTucXtAOvWDSHFF.woff2
curl -o pxiGyp8kv8JHgFVrLPTufntAOvWDSHFF.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiGyp8kv8JHgFVrLPTufntAOvWDSHFF.woff2
curl -o pxiGyp8kv8JHgFVrLPTucHtAOvWDSA.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiGyp8kv8JHgFVrLPTucHtAOvWDSA.woff2
curl -o pxiByp8kv8JHgFVrLFj_Z11lFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLFj_Z11lFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLFj_Z1JlFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLFj_Z1JlFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLFj_Z1xlFd2JQEk.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLFj_Z1xlFd2JQEk.woff2
curl -o pxiByp8kv8JHgFVrLDz8Z11lFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDz8Z11lFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLDz8Z1JlFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDz8Z1JlFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLDz8Z1xlFd2JQEk.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDz8Z1xlFd2JQEk.woff2
curl -o pxiEyp8kv8JHgFVrJJbecnFHGPezSQ.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJbecnFHGPezSQ.woff2
curl -o pxiEyp8kv8JHgFVrJJnecnFHGPezSQ.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJnecnFHGPezSQ.woff2
curl -o pxiEyp8kv8JHgFVrJJfecnFHGPc.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJfecnFHGPc.woff2
curl -o pxiByp8kv8JHgFVrLGT9Z11lFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLGT9Z11lFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLGT9Z1JlFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLGT9Z1JlFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLGT9Z1xlFd2JQEk.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLGT9Z1xlFd2JQEk.woff2
curl -o pxiByp8kv8JHgFVrLEj6Z11lFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLEj6Z11lFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLEj6Z1JlFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLEj6Z1JlFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLEj6Z1xlFd2JQEk.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLEj6Z1xlFd2JQEk.woff2
curl -o pxiByp8kv8JHgFVrLCz7Z11lFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLCz7Z11lFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLCz7Z1JlFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLCz7Z1JlFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLCz7Z1xlFd2JQEk.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLCz7Z1xlFd2JQEk.woff2
curl -o pxiByp8kv8JHgFVrLDD4Z11lFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDD4Z11lFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLDD4Z1JlFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDD4Z1JlFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLDD4Z1xlFd2JQEk.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLDD4Z1xlFd2JQEk.woff2
curl -o pxiByp8kv8JHgFVrLBT5Z11lFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLBT5Z11lFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLBT5Z1JlFd2JQEl8qw.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLBT5Z1JlFd2JQEl8qw.woff2
curl -o pxiByp8kv8JHgFVrLBT5Z1xlFd2JQEk.woff2 https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLBT5Z1xlFd2JQEk.woff2
